version: "3"
services:
  client:
    hostname: client
    image: chiedu/multi-docker-client
    mem_limit: 128m
  nginx:
    hostname: nginx
    image: chiedu/multi-docker-fib-nginx
    mem_limit: 128m
    ports:
      - 80:80
  fib-calculator:
    hostname: fib-calculator
    image: chiedu/multi-docker-fib-calculator
    mem_limit: 128m
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
  api:
    hostname: api
    image: chiedu/multi-docker-api
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - PG_USER=${PG_USER}
      - PG_HOST=${PG_HOST}
      - PG_DATABASE=${PG_DATABASE}
      - PG_PASSWORD=${PG_PASSWORD}
      - PG_PORT=${PG_PORT}
