name: "Main workflow to build and deploy multi-container images"
on:
  push:
    branches:
      - main

jobs:
  # Test the "client" application first
  test:
    uses: ./.github/workflows/test.yml
  build_and_push_images:
    name: Build and push images to Docker Hub
    needs: test
    runs-on: ubuntu-latest
    steps:
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - run: docker build --progress=plain -t chiedu/multi-docker-api ./api
      - run: docker build --progress=plain -t chiedu/multi-docker-client ./client
      - run: docker build --progress=plain -t chiedu/multi-docker-fib-calculator ./fib-calculator
      - run: docker build --progress=plain -t chiedu/multi-docker-fib-nginx ./nginx
    # TODO push to docker hub
