name: "Main workflow to build and deploy multi-container images"
on:
  push:
    branches:
      - main

jobs:
  # Test the "client" application first
  test:
    uses: ./.github/workflows/test.yml
    secrets:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_ACCESS_TOKEN: ${{ secrets.DOCKER_ACCESS_TOKEN }}
  build_and_push_images:
    name: Build and push images to Docker Hub
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_ACCESS_TOKEN }}
      - run: docker build --progress=plain -t chiedu/multi-docker-api ./api
      - run: docker build --progress=plain -t chiedu/multi-docker-client ./client
      - run: docker build --progress=plain -t chiedu/multi-docker-fib-calculator ./fib-calculator
      - run: docker build --progress=plain -t chiedu/multi-docker-fib-nginx ./nginx
        # Push all images to docker hub
      - run: docker push chiedu/multi-docker-api
      - run: docker push chiedu/multi-docker-client
      - run: docker push chiedu/multi-docker-fib-calculator
      - run: docker push chiedu/multi-docker-fib-nginx
      # Create zip file of repo for EB deployment: S3 & EC2
      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'
      # Deploy to EB
      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}
          application_name: multi-docker
          environment_name: Multi-docker-env
          existing_bucket_name: elasticbeanstalk-eu-north-1-277707125544
          region: eu-north-1
          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
